"""<create tables>

Revision ID: 1121dc2836e4
Revises: 1224ed2dbb16
Create Date: 2023-09-23 23:52:40.798757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1121dc2836e4'
down_revision = '1224ed2dbb16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baked_goods', sa.Column('bakery_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_baked_goods_bakery_id_bakeries'), 'baked_goods', 'bakeries', ['bakery_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_baked_goods_bakery_id_bakeries'), 'baked_goods', type_='foreignkey')
    op.drop_column('baked_goods', 'bakery_id')
    # ### end Alembic commands ###
