"""<create tables>

Revision ID: 1224ed2dbb16
Revises: a50cde241c4b
Create Date: 2023-09-23 23:44:41.913644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1224ed2dbb16'
down_revision = 'a50cde241c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baked_goods', sa.Column('name', sa.String(), nullable=True))
    op.add_column('baked_goods', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('baked_goods', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('baked_goods', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('bakeries', sa.Column('name', sa.String(), nullable=True))
    op.add_column('bakeries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('bakeries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bakeries', 'updated_at')
    op.drop_column('bakeries', 'created_at')
    op.drop_column('bakeries', 'name')
    op.drop_column('baked_goods', 'updated_at')
    op.drop_column('baked_goods', 'created_at')
    op.drop_column('baked_goods', 'price')
    op.drop_column('baked_goods', 'name')
    # ### end Alembic commands ###
